import { Exercise } from './types';

export const PRESET_EXERCISES: Omit<Exercise, 'createdAt' | 'updatedAt'>[] = [
  // ===== PAD - Beginner =====
  {
    id: 'preset-single-stroke',
    name: '单击 (Single Stroke)',
    category: 'pad',
    level: 'beginner',
    description: 'RLRL 交替单击，最基础的速度训练',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['核心指标', '热身'],
    isCustom: false,
  },
  {
    id: 'preset-double-stroke',
    name: '双击 (Double Stroke)',
    category: 'pad',
    level: 'beginner',
    description: 'RRLL 双击，手腕控制力训练',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['核心指标', '热身'],
    isCustom: false,
  },
  {
    id: 'preset-paradiddle',
    name: '复合跳 (Paradiddle)',
    category: 'pad',
    level: 'beginner',
    description: 'RLRR LRLL 复合跳，协调性训练',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['核心指标'],
    isCustom: false,
  },
  {
    id: 'preset-accent-shift',
    name: '重音移位',
    category: 'pad',
    level: 'beginner',
    description: '重音在1拍、2拍、3拍、4拍轮换',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['热身', '重音'],
    isCustom: false,
  },
  {
    id: 'preset-tap-accent',
    name: '重音轻音',
    category: 'pad',
    level: 'beginner',
    description: 'tap-accent 组合，力度控制训练',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['热身', '力度'],
    isCustom: false,
  },
  {
    id: 'preset-16th-8th',
    name: '前十六后八',
    category: 'pad',
    level: 'beginner',
    description: '前十六后八节奏型练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['节奏型'],
    isCustom: false,
  },
  {
    id: 'preset-8th-16th',
    name: '前八后十六',
    category: 'pad',
    level: 'beginner',
    description: '前八后十六节奏型练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['节奏型'],
    isCustom: false,
  },
  {
    id: 'preset-syncopation',
    name: '切分音',
    category: 'pad',
    level: 'beginner',
    description: '切分节奏练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['节奏型'],
    isCustom: false,
  },
  {
    id: 'preset-triplet',
    name: '三连音',
    category: 'pad',
    level: 'beginner',
    description: '基础三连音练习',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['热身', '三连音'],
    isCustom: false,
  },
  // ===== PAD - Intermediate =====
  {
    id: 'preset-flam',
    name: 'Flam',
    category: 'pad',
    level: 'intermediate',
    description: '装饰音 Flam 练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['装饰音'],
    isCustom: false,
  },
  {
    id: 'preset-drag',
    name: 'Drag',
    category: 'pad',
    level: 'intermediate',
    description: '装饰音 Drag 练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['装饰音'],
    isCustom: false,
  },
  {
    id: 'preset-paradiddle-variants',
    name: 'Paradiddle 变体',
    category: 'pad',
    level: 'intermediate',
    description: 'Double/Triple Paradiddle 等变体',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['复合跳'],
    isCustom: false,
  },
  {
    id: 'preset-accent-triplet',
    name: '带重音三连音',
    category: 'pad',
    level: 'intermediate',
    description: '三连音中加入重音移位',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['三连音', '重音'],
    isCustom: false,
  },
  {
    id: 'preset-mixed-16-8',
    name: '八十六混合',
    category: 'pad',
    level: 'intermediate',
    description: '八分音符和十六分音符混合节奏型',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['混合练习'],
    isCustom: false,
  },
  // ===== KIT - Beginner =====
  {
    id: 'preset-8beat',
    name: '8 Beat',
    category: 'kit',
    level: 'beginner',
    description: '基础八分音符节奏型',
    defaultBpm: 80,
    defaultTimeSignature: [4, 4],
    tags: ['节奏型'],
    isCustom: false,
  },
  {
    id: 'preset-16beat',
    name: '16 Beat',
    category: 'kit',
    level: 'beginner',
    description: '基础十六分音符节奏型',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['节奏型'],
    isCustom: false,
  },
  {
    id: 'preset-hihat-open-close',
    name: '踩镲开合',
    category: 'kit',
    level: 'beginner',
    description: '踩镲开合控制练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['踩镲'],
    isCustom: false,
  },
  {
    id: 'preset-foot-single',
    name: '单踩协调',
    category: 'kit',
    level: 'beginner',
    description: '单踩+手的基础协调练习',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['热身', '双脚'],
    isCustom: false,
  },
  // ===== KIT - Intermediate =====
  {
    id: 'preset-linear',
    name: '线性节奏',
    category: 'kit',
    level: 'intermediate',
    description: '手脚不同时击打的线性节奏',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['线性'],
    isCustom: false,
  },
  {
    id: 'preset-ghost-note',
    name: 'Ghost Note',
    category: 'kit',
    level: 'intermediate',
    description: '幽灵音练习，增加律动感',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['律动'],
    isCustom: false,
  },
  {
    id: 'preset-foot-double',
    name: '双踩交替',
    category: 'kit',
    level: 'intermediate',
    description: '双脚交替踩踏练习',
    defaultBpm: 60,
    defaultTimeSignature: [4, 4],
    tags: ['双脚'],
    isCustom: false,
  },
  // ===== MUSICALITY - Beginner =====
  {
    id: 'preset-dynamics',
    name: '力度控制',
    category: 'musicality',
    level: 'beginner',
    description: 'ppp 到 fff 的力度渐变练习',
    defaultBpm: 70,
    defaultTimeSignature: [4, 4],
    tags: ['力度'],
    isCustom: false,
  },
  {
    id: 'preset-shuffle',
    name: '基础 Shuffle',
    category: 'musicality',
    level: 'beginner',
    description: 'Shuffle 节奏感训练',
    defaultBpm: 80,
    defaultTimeSignature: [4, 4],
    tags: ['Shuffle'],
    isCustom: false,
  },
  // ===== MUSICALITY - Intermediate =====
  {
    id: 'preset-swing',
    name: 'Swing',
    category: 'musicality',
    level: 'intermediate',
    description: 'Swing 摇摆节奏练习',
    defaultBpm: 100,
    defaultTimeSignature: [4, 4],
    tags: ['Swing', 'Jazz'],
    isCustom: false,
  },
  {
    id: 'preset-funk-groove',
    name: 'Funk Groove',
    category: 'musicality',
    level: 'intermediate',
    description: 'Funk 律动练习',
    defaultBpm: 90,
    defaultTimeSignature: [4, 4],
    tags: ['Funk', '律动'],
    isCustom: false,
  },
];

export const CORE_EXERCISE_IDS = [
  'preset-single-stroke',
  'preset-double-stroke',
  'preset-paradiddle',
];
